=begin
#dsgt

#DSGT

The version of the OpenAPI document: 1.0.0
Contact: achau3910@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

module OpenapiClient
  VERSION = '1.0.0'
end
