/* tslint:disable */
/* eslint-disable */
/**
 * dsgt
 * DSGT
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: achau3910@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * DSGT Item
 * @export
 * @interface DSGT
 */
export interface DSGT {
    /**
     * 
     * @type {string}
     * @memberof DSGT
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DSGT
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DSGT
     */
    purpose?: string;
    /**
     * 
     * @type {string}
     * @memberof DSGT
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof DSGT
     */
    date?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof DSGT
     */
    completed?: boolean;
}

export function DSGTFromJSON(json: any): DSGT {
    return DSGTFromJSONTyped(json, false);
}

export function DSGTFromJSONTyped(json: any, ignoreDiscriminator: boolean): DSGT {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'purpose': !exists(json, 'purpose') ? undefined : json['purpose'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
    };
}

export function DSGTToJSON(value?: DSGT | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'purpose': value.purpose,
        'url': value.url,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'completed': value.completed,
    };
}

