=begin
#dsgt

#DSGT

The version of the OpenAPI document: 1.0.0
Contact: achau3910@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for create_dsgt
  # Create a DSGT
  # Creates a new instance of a &#x60;DSGT&#x60;.
  # @param dsgt A new &#x60;DSGT&#x60; to be created.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_dsgt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_dsgt
  # Delete a DSGT
  # Deletes an existing &#x60;DSGT&#x60;.
  # @param dsgt_id A unique identifier for a &#x60;DSGT&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_dsgt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_dsgt
  # Get a DSGT
  # Gets the details of a single instance of a &#x60;DSGT&#x60;.
  # @param dsgt_id A unique identifier for a &#x60;DSGT&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [DSGT]
  describe 'get_dsgt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_dsgts
  # List All DSGTS
  # Gets a list of all &#x60;DSGT&#x60; entities.
  # @param [Hash] opts the optional parameters
  # @return [Array<DSGT>]
  describe 'get_dsgts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_dsgt
  # Update a DSGT
  # Updates an existing &#x60;DSGT&#x60;.
  # @param dsgt_id A unique identifier for a &#x60;DSGT&#x60;.
  # @param dsgt Updated &#x60;DSGT&#x60; information.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_dsgt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
