version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  netlify_deployment:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Netlify deployment
          command: curl -X POST -d {} ${hook}

workflows:
  heroku_deploy:
    jobs:
      - build
      - netlify_deployment: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main
